---
title: "RWorksheet_Lomibao#3b"
author: "lomibao"
date: "2024-10-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.A
```{r}

dataf <- data.frame(
  Respondents = c(1:20),
  Sex = c(2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2),
  Fathers_Occupation = c(1, 3, 3, 3, 1, 2, 3, 1, 1, 1, 3, 2, 1, 3, 3, 1, 3, 1, 2, 1) ,
  Persons_at_Home =  c(5, 7, 3, 8, 5, 9, 6, 7, 8, 4, 7, 5, 4, 7, 8, 8, 3, 11, 7, 6),
  Siblings_at_School =  c(6, 4, 4, 1, 2, 1, 5, 3, 1, 2, 3, 2, 5, 5, 2, 1, 2, 5, 3, 2),
  Types_of_Houses = c(1, 2, 3, 1, 1, 3, 3, 1, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 3, 2)
)
dataf
```
B.It shows the summary of the data such as mean, median, max, min and etc. 
```{r}
summary(dataf)
```
C. No its 2.95. You could see it at the data itself.
D.
```{r}
subf <- dataf[1:2 , ]
subf
```
E.
```{r}
ot_subf <- dataf[c(3,5) , c(2,4)]
ot_subf
```
F.
```{r}
types_houses <- dataf[ , "Types_of_Houses"]
types_houses
```
G.
```{r}
mal_res <- subset(dataf, Sex == 1 & Fathers_Occupation == 1)
mal_res
```
H.
```{r}
fem_res <- subset(dataf, Sex ==2 & Siblings_at_School >=5)
fem_res
```
2.It show what is within the dataframe such as objects, variables and data types.
```{r}
df = data.frame(Ints=integer(),

Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(df))
```
3.
```{r}
#HouseholdData <- read.csv("/cloud/project/HouseholdData.csv")
```

