---
title: "RWorksheet_Lomibao#5(lomibao and rabago)"
author: "lomibao and rabago"
date: "2024-11-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

```
1.
```{r}
library("rvest")
library("polite")
library("httr")
library("dplyr")

url <- "https://www.imdb.com/chart/toptv/"
  
 session <- bow(url, 
                 user_agent = "Student education purpose")
 session

 session_page <- scrape(session)  
 page <- read_html(url)

rank_title <-character(0)
links <- character(0)

#title <- vector("character", length = 50 )

#   for(i in 1:52){
#  title[i] <- session_page%>%html_nodes(paste0("h3.ipc-title__te # xt(',i')"))%>%html_text()
 #  }

 # print(title)
 
 title <- session_page%>%html_nodes('h3.ipc-title__text')%>%html_text()
 title

```
Creating as a Dataframe.
```{r}
title_list <- as.data.frame(title[1:50])
colnames(title_list)<-"ranks"

```
Spliting the Data Frame 
```{r}
split_df <- strsplit(as.character(title_list$ranks),".",fixed = TRUE)
split_df<- data.frame(do.call(rbind,split_df))
split_df
```
renaming the columns
```{r}
split_df<-split_df[-c(3,4)]
colnames(split_df)<- c("Ranks","Titles")
split_df
```
creating a Csv.file
```{r}
rank_title<-data.frame(
  rank_title = split_df
)
#write.csv(rank_title = "title.csv")
```

