---
title: "RWorksheet_Lomibao#4a"
author: "lomibao"
date: "2024-10-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1.A
```{r}
shoe_heightdf <- data.frame(Shoe_size = c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,7.5,10.5,8.5,12.0,10.5,13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0), Height=c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0), Gender=c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M"))
shoe_heightdf
```
B.
```{r}
male_subs<- subset(shoe_heightdf, Gender == "M", select = c(Gender, Shoe_size, Height))
male_subs
fem_subs<- subset(shoe_heightdf, Gender == "F", select = c(Gender, Shoe_size, Height))
fem_subs
            
```
C.
```{r}
mean_of_respo <- sapply(shoe_heightdf[, c("Shoe_size","Height")], mean, na.rm = TRUE)
mean_of_respo
```
D.Yes, Based on data the higher the person the larger the shoe size specially the male / "M"
2.
```{r}
months_vector <- c("March","April","January","November","January","September","October","September","Novemeber","August","Janaury","November","November","February","May","August","July","December","August","August","September","November","February","April")
factor_months_vector <- factor(months_vector)
factor_months_vector
```
3.
```{r}
summary(months_vector)
summary(factor_months_vector)
```
4.
```{r}
Direction <- c("East","West","North")
Frequency <- c(1,4,3)
factor_data <- Direction
new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)
```
5.
```{r}
Import_March <- read.table("/cloud/project/import_march - Sheet1.csv")
Import_March
```
6.
```{r}
num <- as.integer(readline(prompt = "Enter a number between 1 to 50: "))
if(!is.na(num) && num == 20) {
  print("The number is beyond the range of 1 to 50 ")
}else{
  print("TRUE")
}

if(!is.na(num) && num>=1 && num<=50){
  num
}else{
  print("The number selected is beyond the range of 1 to 50.")
}
```
7.
```{r}
price <- as.numeric(readline(prompt="Enter Price: "))
min_bills <- function(price) {
bills_used <- 0

if (!is.na(price) && price >= 1000) {
bills_used <- bills_used + price %/% 1000
price <- price %% 1000
}
4
if (!is.na(price) && price >= 500) {
bills_used <- bills_used + price %/% 500
price <- price %% 500
}
if (!is.na(price) && price >= 200) {
bills_used <- bills_used + price %/% 200
price <- price %% 200
}
if (!is.na(price) && price >= 100) {
bills_used <- bills_used + price %/% 100
price <- price %% 100
}
if (!is.na(price) && price >= 50) {
bills_used <- bills_used + price %/% 50
price <- price %% 50
}
return(bills_used)
}
min_bills(price)

```
8.A.
```{r}
grade <- data.frame(Name = c("Annie", "Thea", "Steve","Hanna"),  Grade1 = c(85,65,75,95),Grade2 = c(65,75,55,75),Grade3 = c(85, 90, 80, 100),Grade4 = c(100, 90, 85, 90))
```
B.
```{r}
avg_scores <- rowSums(grade[,-1]) / (ncol(grade) - 1)
if (any(avg_scores > 90)) {
high_avg_names <- grade$Name[avg_scores > 90]
high_avg_scores <- avg_scores[avg_scores > 90]
cat(paste(high_avg_names, " average grade this semester is ", high_avg_scores, ".\n", sep = ""))
}else{
cat("No student's average grade is over 90.\n")
}
```
C.
```{r}
test_avg <- colSums(grade[,-1]) / nrow(grade)
if (any(test_avg < 80)) {
hard_tests <- which(test_avg < 80)
cat(paste("The", hard_tests, "th test was difficult.\n"))
} else {
cat("All tests had average scores of 80 or above.\n")
}

```
D.
```{r}
highest_scores <- apply(grade[,-1], 1, function(x) sort(x, decreasing = TRUE)[1])
if (any(highest_scores > 90)) {
high_score_names <- grade$Name[highest_scores > 90]
high_scores <- highest_scores[highest_scores > 90]
cat(paste(high_score_names, "'s highest grade this semester is ", high_scores, ".\n"))
} else {
cat("No student's highest grade exceeded 90.\n")
}

```

